name: flutter_alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.2
homepage: https://github.com/hautvfami/flutter-alice

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^4.0.6
  chopper: ^4.0.6
  overlay_support: ^2.0.1
  share: ^2.0.4
  rxdart: ^0.27.4
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.6.10+2